#!/bin/bash
echo "enter mark 1:"
read m1
echo "enter mark 2:"
read m2
echo "enter mark 3:"
read m3
total=`expr $m1 + $m2 + $m3`
echo "total marks:"$total
percentage=`expr $total / 3`
echo "percentage:"$percentage %
if [ $percentage -ge 90 ]
then
echo "S grade"
if [ $percentage -ge 80 ]
then
echo "A grade"
if [ $percentage -ge 70 ]
then
echo "B grade"
elif [ $percentage -ge 50 ]
then
echo "C grade"
else
echo "failed"
fi
