#!/bin/bash
echo "enter the number"
read a
echo 'enter another number'
read b 
echo "what do yoou want to do? (1 to 4) "
echo "1) addition"
echo "2) subtraction"
echo "3) multiplication"
echo "4) division"
echo " enter the choice"
read n 
case "$n" in
1) echo "the sum of $a and $d is `expr $a +$b`";;
2) echo "the difference between $a and $b is `expr $a - $b`";;
3) echo "the product is `expr $a \* $b`";;
4) echo "the division is `expr $a / $b`";;
esac
